apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: longpb-cluster
  region: us-east-1

nodeGroups:
  - name: nodegroup-1
    instanceType: t2.small
    desiredCapacity: 2
    privateNetworking: true
    iam:
      withAddonPolicies:
        autoScaler: true
        albIngress: true
        imageBuilder: true